# Generated by Django 6.1.1 on 2026-09-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('uploaded', 'Uploaded'), ('pending approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='', help_text='Stores status prior to archiving for restoration on unarchive.', max_length=25),
        ),
    ]
