# Generated by Django 6.1.1 on 2026-09-27 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_document_previous_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='The action name (e.g. approve, reject).', max_length=50)),
                ('details', models.TextField(blank=True, default='', help_text='Details or comments regarding the action.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Date and time when the action occurred.')),
                ('document', models.ForeignKey(blank=True, help_text='Document associated with the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='documents.document')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
