# Generated by Django 6.1.1 on 2026-09-27 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('documents', '0002_document_previous_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the approval workflow.', max_length=20)),
                ('comment', models.TextField(blank=True, default='', help_text='Optional comment from the reviewer.')),
                ('decided_date', models.DateTimeField(blank=True, help_text='Date and time when the approval decision was made.', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, help_text='User who decided this approval.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_approvals', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(help_text='The document awaiting or having undergone approval.', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='documents.document')),
            ],
            options={
                'verbose_name': 'Approval',
                'verbose_name_plural': 'Approvals',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('tender', 'Tender'), ('contract', 'Contract'), ('report', 'Report'), ('invoice', 'Invoice'), ('legal', 'Legal'), ('safety circular', 'Safety Circular'), ('other', 'Other')], help_text='Document type that this rule applies to.', max_length=30)),
                ('approver_role', models.CharField(choices=[('officer', 'Officer'), ('admin', 'Admin')], help_text='Role required to approve documents matching this type and department.', max_length=20)),
                ('department', models.ForeignKey(help_text='Department that this rule applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='accounts.department')),
            ],
            options={
                'verbose_name': 'Approval Rule',
                'verbose_name_plural': 'Approval Rules',
                'ordering': ['department', 'document_type'],
                'unique_together': {('document_type', 'department')},
            },
        ),
    ]
