# Generated by Django 6.1.1 on 2026-09-27 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Notification message text.', max_length=255)),
                ('link', models.CharField(blank=True, default='', help_text='Optional relative URL to send the user to when clicked.', max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Designates whether this notification has been read.')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the notification was created.')),
                ('recipient', models.ForeignKey(help_text='User who receives the notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_date'],
            },
        ),
    ]
